version: '3.2'
services:
  flask_app:
    build: ./app
    volumes: 
      - ./app:/app
    ports:
      - 5000:5000

  db_ehex:
    image: postgres:11.2
    container_name: db_ehex
    env_file:
      - web-variables.env
    ports:
      - "5432:5432"